activity_monitor/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from monitor import views

urlpatterns = [
    path ('', include('monitor.urls')),
    path('/admin/', admin.site.urls),
]

"""
   path('', views.homepage, name='homepage'),
    path('/sensor/', views.sensor, name='sensor'),
    path('/info/', views.info, name='info'),
"""

monitor/urls.py
from django.urls import path
from monitor import views

app_name = 'monitor'

urlpatterns = [
    path ('', views.homepage, name ='homepage'),
    path('sensor/', views.sensor, name = 'sensor'),
    path('info/', views.info, name='info'),
    path('register-sensor/', views.registerSensor, name='register-sensor'),
    path('add-record/', views.addRecord, name='add-record'),
]

monitor/models.py
from django.db import models
import numpy as np
#from ndarraydjango.fields import NDArrayField
#from ndarray import NDArrayField


# UP FOR MASSIVE CHANGES AS WE NEED TO DISCUSS THESE!

class Model(models.Model):
    #vec1 = NDArrayField(shape=(32, 4), dtype=np.float64)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Models'

class SensorProfile(models.Model):
    id = models.CharField(primary_key=True, editable=False, max_length=4)
    location = models.CharField(max_length=30)

    class Meta:
        verbose_name_plural = 'SensorProfiles'

class LoggingRecord(models.Model):
    time_logged = models.TimeField()
    sound_category = models.CharField(max_length=30)
    sensor = models.ForeignKey(SensorProfile, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'LoggingRecords'

monitor/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from monitor.models import SensorProfile, LoggingRecord

def homepage(request):
    context_dict = {}
    return render(request,'monitor_templates/homepage.html', context=context_dict)

def sensor(request):
    context_dict = {}
    return render(request, 'monitor_templates/sensor.html', context=context_dict)

def info(request):
    context_dict = {}
    return render(request, 'monitor_templates/info.html', context=context_dict)  


def registerSensor(request):
    if request.method == 'GET':
        try:
            new_sensor_id = request.GET.get('id')
            if new_sensor_id is None:
                return HttpResponse('ERR02 No-id-Field-Given')
            if SensorProfile.objects.filter(id=new_sensor_id).exists():
                return HttpResponse("ERR03 Sensor-already-registered")
            else:
                new_sensor = SensorProfile(id=new_sensor_id, location="")
                new_sensor.save()
                return HttpResponse('Successful-Registration')
        except KeyError:
            return HttpResponse('ERR02 No-id-Field-Given')
        except Exception as e:
            print(e)
            return HttpResponse('ERR00 Unknown-Error')
    else:
        return HttpResponse('ERR01 Incorrect-Request-Type')


def addRecord(request):
    if request.method == 'POST':
        try:
            id = request.POST.get('id')
            time = request.POST.get('time')
            data = request.POST.get('data')
            decision = ""#call NNModel object and pass it the data, then put the result here
            if SensorProfile.objects.filter(sensor=id, time_logged=time).exists():
                raise Exception("ERR13 Sound-Already-Logged")
            else:
                new_record = LoggingRecord(time_logged=time, sound_category=decision, sensor=id)
                new_record.save()
                return HttpResponse('Sound-Logged-Successfully')
        except KeyError:
            return HttpResponse('ERR12 Incorrect-fields-given')
        except Exception as e:
            print(e)
            return HttpResponse('ERR00 Unknown-Error')
    else:
        return HttpResponse('ERR11 Incorrect-Request-Type')

templates/monitor_templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'images/images.jpeg' %}">
    <title>
        Monitor - {% block title_block %}Monitor{% endblock %}
    </title>
    <!--
    <link rel="stylesheet" href="{% static 'style/topBar.css' %}" type="text/css" />

    <script
            src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js">
    </script>
    <script src="{% static "js/stream-jquery.js" %}"></script>
    <script src="{% static "js/stream-ajax.js" %}" type="text/javascript"></script>
    -->
</head>
<body>
    <div>
        <h3 class="name">Esp32 Sensor</h3>
        <div class="navButtons">
            <li><a href="{% url 'monitor:homepage' %}">Homepage</a></li>
            <li><a href="{% url 'monitor:sensor' %}">sensor</a></li>
            <li><a href="{% url 'monitor:info' %}">info</a></li>
        </div>
        <div id="content", name="content", class="main">
            <br/>
            {% block body_block %}
            {% endblock %}
        </div>
    </div>
</div>
<!-- Bootstrap core JavaScript
================================================== 
Placed at the end of the document so the pages load faster 
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js"></script>
IE10 viewport hack for Surface/desktop Windows 8 bug 
<script src="http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
-->
</body>
</html>

templates/monitor_templates/homepage.html
<! DOCTYPE html>

{% load static %}

<html>
    <head>
        <title> Homepage </title>
    </head>

    <body> 
        <h1> Welcome to the homepage </h1>
        <div> 
            <a href="/sensor/"> Sensor page</a><br/>
            <a href="/info/"> Any Other Information</a><br/>
        </div>
    </body>
    </html>

templates/monitor_templates/info.html
{% extends "monitor_templates/base.html" %}
{% block body_block%}
    <button onclick="window.location.href='https://stgit.dcs.gla.ac.uk/team-project-h/2022/sh08/sh08-main/-/wikis/home';">
    Click Here for Wiki
{% endblock %}

templates/monitor_templates/sensor.html
{% extends "monitor_templates/base.html" %}
{% block body_block%}
    <p>sensor</p>
{% endblock %}